### PR TITLE
Pass shell env to metals

### PR DESCRIPTION
**Pull request by WeetHet**
Fixed environment not being passed to metals, breaking local nix-based installations

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]

**Comment by tgodzik** [comment]
@hmemcpy anything against the change?

**Comment by hmemcpy** [comment]
Absolutely not, please go ahead!
I apologize, I don't have enough capacity to maintain this extention lately, so any changes are welcome :)

**Comment by WeetHet** [comment]
Wait, please test it first. I can't build dev extensions for some reason so I'm not sure if it works :)

**Comment by WeetHet** [comment]
> Anyone has it setup and can quickly check? I am afraid I will not have time to do it.

Okay, I've borrowed a friend's laptop, and it seems to be working fine, feel free to merge. Also, we need to make a PR to the extensions repo to update the extension, do I do it, or would you do that?

**Comment by tgodzik** [comment]
> > Anyone has it setup and can quickly check? I am afraid I will not have time to do it.
> 
> Okay, I've borrowed a friend's laptop, and it seems to be working fine, feel free to merge. Also, we need to make a PR to the extensions repo to update the extension, do I do it, or would you do that?

It would be cool if you could, thanks!

**Comment by filipwiech** [comment]
@tgodzik Hey, I have pushed an update to the Zed extensions repository to update Scala plugin to the current version 0.0.4 (at the commit b8ae0d4). Just letting you know, since you might probably want to tag it here, like the previous releases. :+1:

**Comment by tgodzik** [comment]
Thanks! Added

**Pull request merged**
