### PR TITLE
chore: add documentation for running scalatest tests and running main

### PR DESCRIPTION
**Pull request by imclem**
@tgodzik as discussed in #29 here's a PR for documenting how to run main and tests.

### CODE REVIEW

**Review by tgodzik — APPROVED** [review]
Thanks!

**Comment by imclem** [comment]
You are welcome. Do you know when is the next release ? BTW there is no tag for 0.1.0

**Comment by tgodzik** [comment]
I must confess I am not 100% sure how the releases of the plugin are done for Zed. I am just helping out since @hmemcpy doesn't have time currently.

I will update the tag and if you know how to release we can do it since I guess it's only the case of bumping the version like in https://github.com/scalameta/metals-zed/pull/27/files ?

**Comment by tgodzik** [comment]
I added the tag for 0.1.0

**Comment by imclem** [comment]
> I must confess I am not 100% sure how the releases of the plugin are done for Zed. I am just helping out since @hmemcpy doesn't have time currently.
> 
> I will update the tag and if you know how to release we can do it since I guess it's only the case of bumping the version like in https://github.com/scalameta/metals-zed/pull/27/files ?

I've never done that either, but I guess it's enough, can you create a new release for 0.1.1 ? Or I can do the update on my fork if you want ?

> I added the tag for 0.1.0

Thanks

**Comment by tgodzik** [comment]
I think it's just the case of sending a PR with an update, feel free to open it!

**Comment by imclem** [comment]
done thanks

**Pull request merged**
